##add hostname, port number and db name properly
jdbcUrl=jdbc:mysql://xx.xx.xx.xx:nnnn/dbname
dataSource.user=username
dataSource.password=pwd
dataSource.maximumPoolSize=100
dataSource.minimumIdle=100
dataSource.connectionTimeout=30000
dataSource.cachePrepStmts=true
dataSource.prepStmtCacheSize=250
dataSource.prepStmtCacheSqlLimit=2048
